name: BitcoinPriceChecker
options:
  bundleIdPrefix: Suto.Kotaro
fileGroups:
  - .github
  - Dangerfile.swift
  - project.yml
  - README.md
  - LICENSE.md
  - .gitignore
targets:
  BitcoinPriceChecker:
    platform: iOS
    type: application
    sources:
      - BitcoinPriceChecker
  BitcoinPriceCheckerTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - BitcoinPriceCheckerTests/
    scheme:
      testTargets:
        - BitcoinPriceCheckerTests
      gatherCoverageData: true
  BitcoinPriceCheckerUITests:
    platform: iOS
    type: bundle.ui-testing
    sources:
      - BitcoinPriceCheckerUITests/
    scheme:
      testTargets:
        - BitcoinPriceCheckerUITests
      gatherCoverageData: true
