name: BitcoinPriceChecker
options:
  bundleIdPrefix: Suto.Kotaro
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    exactVersion: 5.4.3
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    exactVersion: 6.2.0

targets:
  BitcoinPriceChecker:
    platform: iOS
    type: application
    sources:
      - BitcoinPriceChecker
    dependencies:
      - package: Alamofire
      - package: RxSwift
      - package: RxSwift
        product: RxRelay
      - package: RxSwift
        product: RxCocoa
  BitcoinPriceCheckerTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - BitcoinPriceCheckerTests/
    scheme:
      testTargets:
        - BitcoinPriceCheckerTests
      gatherCoverageData: true
  BitcoinPriceCheckerUITests:
    platform: iOS
    type: bundle.ui-testing
    sources:
      - BitcoinPriceCheckerUITests/
    scheme:
      testTargets:
        - BitcoinPriceCheckerUITests
      gatherCoverageData: true
